const { app, BrowserWindow } = require('electron')
const path = require('path')

// Custom protocol handler to serve files correctly
// This fixes the issue where Next.js absolute paths (/_next/...) fail on file:// protocol
const { protocol, net } = require('electron')
const { URL } = require('url')

// Register scheme privileges before anything else
protocol.registerSchemesAsPrivileged([
    { scheme: 'app', privileges: { secure: true, standard: true, supportFetchAPI: true, corsEnabled: true } }
])

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 1280,
        height: 800,
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
            nodeIntegration: false,
            contextIsolation: true,
            webSecurity: true
        },
        autoHideMenuBar: true,
        backgroundColor: '#ffffff', // Prevent black flash
    })

    const isDev = !app.isPackaged

    if (isDev) {
        mainWindow.loadURL('http://localhost:3000')
        mainWindow.webContents.openDevTools()
    } else {
        // Use custom protocol - this is the key fix
        mainWindow.loadURL('app://harmonic-halo/index.html')

        // Enable DevTools in production for debugging the white screen
        // You can remove this line later when it works perfectly
        // mainWindow.webContents.openDevTools()
    }

    mainWindow.on('closed', function () {
        mainWindow = null
    })
}

app.whenReady().then(() => {
    // Register the protocol handler
    protocol.handle('app', (request) => {
        const urlParsed = new URL(request.url)
        let reqPath = urlParsed.pathname

        if (process.platform === 'win32') {
            // Remove leading slash if necessary, though path.join handles it well usually.
        }

        let filePath = path.join(__dirname, '../out', reqPath)

        // Robust path resolution for Next.js static export
        const fs = require('fs')

        try {
            // Priority 1: Check if .html version exists (e.g. /dashboard -> /dashboard.html)
            // This is crucial because Next.js creates both a folder 'dashboard' and a file 'dashboard.html'
            let htmlCandidate = filePath + '.html'
            if (fs.existsSync(htmlCandidate)) {
                filePath = htmlCandidate
            }
            // Priority 2: Check standard file/directory match
            else if (fs.existsSync(filePath)) {
                if (fs.statSync(filePath).isDirectory()) {
                    // It's a directory, try index.html
                    let indexCandidate = path.join(filePath, 'index.html')
                    if (fs.existsSync(indexCandidate)) {
                        filePath = indexCandidate
                    } else {
                        // Edge case: Directory exists but no index.html (e.g. /dashboard/)
                        // If we are here, we might want to try stripping the trailing slash and adding .html?
                        // But usually reqPath wouldn't have trailing slash if generated by Next.js Link
                    }
                }
                // If it's a file, we use it as is
            }
        } catch (err) {
            // Ignore fs errors, let net.fetch handle the final attempt or fail
        }

        // Return the file content
        return net.fetch(require('url').pathToFileURL(filePath).toString())
    })

    createWindow()
})

app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})

app.on('activate', function () {
    if (mainWindow === null) {
        createWindow()
    }
})
